### ISSUE TITLE
Unused logging levels still incur overhead

### ISSUE THREAD

**Issue by Olipro** [Sonoran-Software/SonoranCADLuaIntegration#28]
This is largely applicable to debug level logging as more than likely the majority of users leave logging levels at default values and so will be printing just about anything else:

Arguments to a logging function are fully evaluated with the result passed into the logging function which then decides whether anything should be done with it or not.

In order to avoid this overhead, something like `debugLog(stuff:match(otherstuff))` should be converted to `debugLog(function() return stuff:match(otherstuff) end)` which avoids doing unnecessary work.

As a piecemeal solution, `debugLog()` could implement a secondary check to determine whether the `type()` of the argument is a function or string if not all callsites are converted in one go, or to accommodate cases where an entirely static string is passed and wrapping it in a function gains nothing.

**Comment by nathanctech** [comment]
Hi,

Thanks for your feedback. Optimizations such as this are accepted but I highly recommend making a pull request with the suggested changes rather than logging it as an issue. The logging is fairly infrequently called after initial bootup so refactoring it is not currently of high priority.

Thanks!

**Comment by nathanctech** [comment]
Deciding to close this issue as wontfix. While there might be a marginal benefit, doing so would requiring updating every single reference to debugLog across our entire plugin library which would cause a headache to users since they would need to update every single plugin. I'll revisit this if there's an actual performance impact in the future.
